typedef long long features;

#define IGL_DURATION "1 << 0"
#define IGL_PROTTYPE "1 << 1"
#define IGL_SERVICE  "1 << 2"
#define IGL_FLAG     "1 << 3"
#define IGL_SRCBYTES "1 << 4"
#define IGL_DSTBYTES "1 << 5"
#define IGL_LAND     "1 << 6"
#define IGL_WRNGFRAG "1 << 7"
#define IGL_URGENT   "1 << 8"
#define IGL_HOT      "1 << 9"
#define IGL_FLOGINS  "1 << 10"
#define IGL_LOGINS   "1 << 11"
#define IGL_NUMCOMP  "1 << 12"
#define IGL_ROOTSHLL "1 << 13"
#define IGL_SUATTMPT "1 << 14"
#define IGL_NUMROOT  "1 << 15"
#define IGL_FCREATS  "1 << 16"
#define IGL_SHELLS   "1 << 17"
#define IGL_FACCESS  "1 << 18"
#define IGL_OUTCMDS  "1 << 19"
