#define ICMP_PROTNUM 1
#define TCP_PROTNUM 6
#define UDP_PROTNUM 17

const char* getIPProtoName(int pnum) {
  if      (pnum == 0)   return "HOPOPT";
  else if (pnum == 1)   return "ICMP";
  else if (pnum == 2)   return "IGMP";
  else if (pnum == 3)   return "GGP";
  else if (pnum == 4)   return "IPv4";
  else if (pnum == 5)   return "ST";
  else if (pnum == 6)   return "TCP";
  else if (pnum == 7)   return "CBT";
  else if (pnum == 8)   return "EGP";
  else if (pnum == 9)   return "IGP";
  else if (pnum == 10)  return "BBN-RCC-MON";
  else if (pnum == 11)  return "NVP2";
  else if (pnum == 12)  return "PUP";
  else if (pnum == 13)  return "ARGUS (deprecated)";
  else if (pnum == 14)  return "EMCON";
  else if (pnum == 15)  return "XNET";
  else if (pnum == 16)  return "CHAOS";
  else if (pnum == 17)  return "UDP";
  else if (pnum == 18)  return "MUX";
  else if (pnum == 19)  return "DCN-MEAS";
  else if (pnum == 20)  return "HMP";
  else if (pnum == 21)  return "PRM";
  else if (pnum == 23)  return "TRUNK-1";
  else if (pnum == 24)  return "TRUNK-2";
  else if (pnum == 25)  return "LEAF-1";
  else if (pnum == 26)  return "LEAF-2";
  else if (pnum == 27)  return "RDP";
  else if (pnum == 28)  return "IRTP";
  else if (pnum == 29)  return "ISO-TP4";
  else if (pnum == 30)  return "NETBLT";
  else if (pnum == 31)  return "MFE-NSP";
  else if (pnum == 32)  return "MERIT-INP";
  else if (pnum == 33)  return "DCCP";
  else if (pnum == 34)  return "3PC";
  else if (pnum == 35)  return "IDPR";
  else if (pnum == 36)  return "XTP";
  else if (pnum == 37)  return "DDP";
  else if (pnum == 38)  return "IDPR-CMTP";
  else if (pnum == 39)  return "TP++";
  else if (pnum == 40)  return "IL";
  else if (pnum == 41)  return "IPv6";
  else if (pnum == 42)  return "SDRP";
  else if (pnum == 43)  return "IPv6-Route";
  else if (pnum == 44)  return "IPv6-Frag";
  else if (pnum == 45)  return "IDRP";
  else if (pnum == 46)  return "RSVP";
  else if (pnum == 47)  return "GRE";
  else if (pnum == 48)  return "DSR";
  else if (pnum == 49)  return "BNA";
  else if (pnum == 50)  return "ESP";
  else if (pnum == 51)  return "AH";
  else if (pnum == 52)  return "I-NLSP";
  else if (pnum == 53)  return "SWIPE (deprecated)";
  else if (pnum == 54)  return "NARP";
  else if (pnum == 55)  return "MOBILE";
  else if (pnum == 56)  return "TLSP";
  else if (pnum == 57)  return "SKIP";
  else if (pnum == 58)  return "IPv6-ICMP";
  else if (pnum == 59)  return "IPv6-NoNxt";
  else if (pnum == 60)  return "IPv6-Opts";
  else if (pnum == 62)  return "CFTP";
  else if (pnum == 64)  return "SAT-EXPAK";
  else if (pnum == 65)  return "KRYPTOLAN";
  else if (pnum == 66)  return "RVD";
  else if (pnum == 67)  return "IPPC";
  else if (pnum == 69)  return "SAT-MON";
  else if (pnum == 70)  return "VISA";
  else if (pnum == 71)  return "IPCV";
  else if (pnum == 72)  return "CPNX";
  else if (pnum == 73)  return "CPHB";
  else if (pnum == 74)  return "WSN";
  else if (pnum == 75)  return "PVP";
  else if (pnum == 76)  return "BR-SAT-MON";
  else if (pnum == 77)  return "SUN-ND";
  else if (pnum == 78)  return "WB-MON";
  else if (pnum == 79)  return "WB-EXPAK";
  else if (pnum == 80)  return "ISO-IP";
  else if (pnum == 81)  return "VMTP";
  else if (pnum == 82)  return "SECURE-VMTP";
  else if (pnum == 83)  return "VINES";
  else if (pnum == 84)  return "IPTM";
  else if (pnum == 85)  return "NSFNET-IGP";
  else if (pnum == 86)  return "DGP";
  else if (pnum == 87)  return "TCF";
  else if (pnum == 88)  return "EIGRP";
  else if (pnum == 89)  return "OSPFIGP";
  else if (pnum == 90)  return "Sprite-RPC";
  else if (pnum == 91)  return "LARP";
  else if (pnum == 92)  return "MTP";
  else if (pnum == 93)  return "AX.25";
  else if (pnum == 94)  return "IPIP";
  else if (pnum == 95)  return "MICP (deprecated)";
  else if (pnum == 96)  return "SCC-SP";
  else if (pnum == 97)  return "ETHERIP";
  else if (pnum == 98)  return "ENCAP";
  else if (pnum == 100) return "GMTP";
  else if (pnum == 101) return "IFMP";
  else if (pnum == 102) return "PNNI";
  else if (pnum == 103) return "PIM";
  else if (pnum == 104) return "ARIS";
  else if (pnum == 105) return "SCPS";
  else if (pnum == 106) return "QNX";
  else if (pnum == 107) return "A/N";
  else if (pnum == 108) return "IPComp";
  else if (pnum == 109) return "SNP";
  else if (pnum == 110) return "Compaq-Peer";
  else if (pnum == 111) return "IPX-in-IP";
  else if (pnum == 112) return "VRRP";
  else if (pnum == 113) return "PGM";
  else if (pnum == 115) return "L2TP";
  else if (pnum == 116) return "DDX";
  else if (pnum == 117) return "IATP";
  else if (pnum == 118) return "STP";
  else if (pnum == 119) return "SRP";
  else if (pnum == 120) return "UTI";
  else if (pnum == 121) return "SMP";
  else if (pnum == 122) return "SM (deprecated)";
  else if (pnum == 123) return "PTP";
  else if (pnum == 124) return "ISIS over IPv4";
  else if (pnum == 125) return "FIRE";
  else if (pnum == 126) return "CRTP";
  else if (pnum == 127) return "CRUDP";
  else if (pnum == 128) return "SSCOPMCE";
  else if (pnum == 129) return "IPLT";
  else if (pnum == 130) return "SPS";
  else if (pnum == 131) return "PIPE";
  else if (pnum == 132) return "SCTP";
  else if (pnum == 133) return "FC";
  else if (pnum == 134) return "RSVP-E2E-IGNORE";
  else if (pnum == 135) return "Mobility Header";
  else if (pnum == 136) return "UDPLite";
  else if (pnum == 137) return "MPLS-in-IP";
  else if (pnum == 138) return "manet";
  else if (pnum == 139) return "HIP";
  else if (pnum == 140) return "Shim6";
  else if (pnum == 141) return "WESP";
  else if (pnum == 142) return "ROHC";
  else if (pnum == 143) return "Ethernet";
  else if (pnum == 144) return "AGGFRAG";
  else if (pnum == 145) return "NSH";
  else return "--";
}
